"""Significance testing for metric differences (small-sample aware).

Annual returns give ~10 observations; t-tests are fragile. Two standard
nonparametric tools, each matched to its statistic:

1. Mean return difference (paired by year): BLOCK bootstrap on the
   H0-recentered difference series (H0: mean diff = 0). The one/two-sided
   p-value is how often the null world produces a mean at least as extreme
   as observed. Blocks of 2 preserve short-range autocorrelation.

2. Volatility difference: paired PERMUTATION test (within-year swaps of
   strat/bench returns). Under H0 the paired series are exchangeable, so
   random swaps generate the null; this is the natural test for a
   non-pairwise statistic like std(strat) - std(bench).

All p-values are two-sided by default; the direction is read off the
sign of the observed difference.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

N_RESAMPLES = 10_000
BLOCK = 2
SEED = 42


def _block_indices(n: int, block: int, rng: np.random.Generator) -> np.ndarray:
    """Sample indices in contiguous blocks (circular bootstrap)."""
    n_blocks = int(np.ceil(n / block))
    starts = rng.integers(0, n, size=n_blocks)
    idx = []
    for s in starts:
        idx.extend((s + np.arange(block)) % n)
    return np.asarray(idx[:n])


def bootstrap_mean_test(
    diff: pd.Series,
    n_boot: int = N_RESAMPLES,
    block: int = BLOCK,
    seed: int = SEED,
) -> tuple[float, float, tuple[float, float]]:
    """Paired block bootstrap for the mean of a difference series.

    Returns (observed_mean, two_sided_p, (ci_lo, ci_hi)).
    Null: mean(diff) = 0, generated by recentering the series at zero and
    block-resampling; p = 2 * min(P(mean* >= obs), P(mean* <= obs)).
    CI: 95% percentile interval from raw (non-recentered) resample means.
    """
    x = diff.dropna().to_numpy(dtype=float)
    n = len(x)
    if n < 4:
        return np.nan, np.nan, (np.nan, np.nan)
    rng = np.random.default_rng(seed)
    obs = float(x.mean())
    centered = x - obs
    null_means = np.empty(n_boot)
    ci_means = np.empty(n_boot)
    for i in range(n_boot):
        idx = _block_indices(n, block, rng)
        null_means[i] = centered[idx].mean()
        ci_means[i] = x[idx].mean()
    p_two = min(1.0, 2 * min(np.mean(null_means >= obs), np.mean(null_means <= obs)))
    lo, hi = np.quantile(ci_means, [0.025, 0.975])
    return obs, float(p_two), (float(lo), float(hi))


def permutation_vol_test(
    strat: pd.Series,
    bench: pd.Series,
    n_perm: int = N_RESAMPLES,
    seed: int = SEED,
) -> tuple[float, float, tuple[float, float]]:
    """Paired permutation test for std(strat) - std(bench).

    Within each year, randomly swap the (strat, bench) pair — under H0
    (exchangeable pairs) this generates the null distribution of the
    volatility difference. Returns (observed_diff, two_sided_p, bootstrap CI).
    """
    df = pd.concat([strat.rename("s"), bench.rename("b")], axis=1).dropna()
    n = len(df)
    if n < 4:
        return np.nan, np.nan, (np.nan, np.nan)
    rng = np.random.default_rng(seed)
    s = df["s"].to_numpy(dtype=float)
    b = df["b"].to_numpy(dtype=float)
    obs = float(np.std(s, ddof=1) - np.std(b, ddof=1))
    perm = np.empty(n_perm)
    boot = np.empty(n_perm)
    for i in range(n_perm):
        flip = rng.random(n) < 0.5
        s2 = np.where(flip, b, s)
        b2 = np.where(flip, s, b)
        perm[i] = np.std(s2, ddof=1) - np.std(b2, ddof=1)
        idx = _block_indices(n, BLOCK, rng)
        boot[i] = np.std(s[idx], ddof=1) - np.std(b[idx], ddof=1)
    p_two = min(1.0, 2 * min(np.mean(perm >= obs), np.mean(perm <= obs)))
    lo, hi = np.quantile(boot, [0.025, 0.975])
    return obs, float(p_two), (float(lo), float(hi))


def compare_portfolios(
    returns: pd.DataFrame,
    benchmark_col: str,
    strategy_cols: list[str] | None = None,
) -> pd.DataFrame:
    """Significance comparison of each strategy vs benchmark (two-sided p)."""
    bench = returns[benchmark_col]
    strategies = strategy_cols or [c for c in returns.columns if c != benchmark_col]

    rows = []
    for col in strategies:
        strat = returns[col]
        aligned = pd.concat([strat, bench], axis=1).dropna()
        if len(aligned) < 4:
            continue

        vol_obs, vol_p, vol_ci = permutation_vol_test(strat, bench)
        mean_obs, mean_p, mean_ci = bootstrap_mean_test(strat - bench)

        rows.append(
            {
                "strategy": col,
                "vol_diff": vol_obs,
                "vol_p": vol_p,
                "vol_CI95": vol_ci,
                "mean_ret_diff": mean_obs,
                "mean_ret_p": mean_p,
                "mean_ret_CI95": mean_ci,
            }
        )
    return pd.DataFrame(rows).set_index("strategy")
